version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32600:8000"
    volumes:
      - ./data/images:/app/data/images
      - ./data/database:/app/data/database/
    env_file:
      - .env
    restart: unless-stopped